name: CD (ssh-agent)

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"    


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set variables
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LOWER=${OWNER_LOWER}" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${OWNER_LOWER}/catty-reminders-app:latest" >> $GITHUB_ENV
          echo "CONTAINER_NAME=catty-reminders" >> $GITHUB_ENV
          echo "APP_DIR=/home/vboxuser/Desktop/DevOps/catty-reminders-app" >> $GITHUB_ENV

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -vvv -p 2452 vboxuser@course.prafdin.ru 'echo OK; uname -a'

      - name: Deploy with Docker Compose on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: vboxuser
          SERVER_HOST: course.prafdin.ru
          SERVER_PORT: 2452
        run: |
          scp -P $SERVER_PORT docker-compose.yml $SERVER_USER@$SERVER_HOST:/home/$SERVER_USER/Desktop/DevOps/catty-reminders-app/docker-compose.yml

          ssh -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "
            set -euxo pipefail
            cd /home/$SERVER_USER/Desktop/DevOps/catty-reminders-app

            docker compose pull

            docker compose up -d --remove-orphans

            docker compose ps
          "