name: Deploy Catty Reminders App

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pytest tests/test_unit.py -q -rA
          pytest tests/test_api.py -q -rA

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash /home/vboxuser/Desktop/DevOps/catty-reminders-app/deploy.sh'
